name: Build Web App
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Create Web Build Folder
        run: |
          mkdir build
          cp index.html build/
          # Apnar kache thaka baki file gulo thakle oigulo automatic chole jabe
          
      - name: Upload Web Artifact
        uses: actions/upload-artifact@v3
        with:
          name: web-build
          path: build/
